### ISSUE TITLE
Mac Trouble 

### ISSUE THREAD

**Issue by cfossace** [phulin/dotfiles#1]
I don't think everything is supported on my machine, I'm getting these weird question marks

<img width="253" alt="screen shot 2017-07-20 at 5 31 40 pm" src="https://user-images.githubusercontent.com/8621171/28439804-8c0ae598-6d71-11e7-9972-89ea30d4e8b3.png">

**Comment by phulin** [comment]
You have to install the Menlo for Powerline font. It should have opened the fonts window when you ran install.sh.
